### ISSUE TITLE
No special sound for new highest score

### ISSUE THREAD

**Issue by MPSharp** [SCCapstone/RubberDuck#263]

**Comment by bgrose** [comment]
There is a sound change for new high score screen implemented in Beta Release. Just tested to confirm using the exe. Confused on creation of bug @MPSharp

**Comment by MPSharp** [comment]
Sounded the same to me, post a video for highest score. Then for making the list.

**Comment by ddkeen** [comment]
https://user-images.githubusercontent.com/77408062/223000035-bd094db2-aec6-49d3-9fc2-0afc14bbbefa.mov

sound for not making the top 10 high scores

**Comment by ddkeen** [comment]
https://user-images.githubusercontent.com/77408062/223000476-77067141-88d0-4eeb-9553-6cf1f1af81d0.mov

sound for making the top 10 high score list

**Comment by ddkeen** [comment]
We do not have a specific sound for a new top high score, only for making a the top 10.

**Comment by MPSharp** [comment]
ok sounds good
