### ISSUE TITLE
Coins is always 0

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/RubberDuck#275]
I get coins, but it is always 0.  Or is it 036? This is confusing.

![image](https://user-images.githubusercontent.com/228704/230661397-be45a41e-7475-4e7f-ae38-dfc2ee8abe85.png)

**Comment by josemvidal** [comment]
Oh, the 0 is a coin.

Yeah, fix that.

**Comment by ddkeen** [comment]
moved asset image to the left so it not confused with the number of coins collected

**Comment by josemvidal** [comment]
**Tip:** When you close an issue by writing code, either fixing a bug or creating a new feature, you should add a link to the git-commit(s) that did it.

This can be done automatically if you just write "closes #X" in the comment of the git-commit or the pull request, where X is the issue number you want to close. See [linking pull requests to issues using keywords](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more information, or [watch this video](https://youtu.be/WMykv2ZMyEQ).

You should also write "#X" on any commit that is for #X. That commit will then get automatically linked to the Issue.

See my [github tips list](https://capstone.cse.sc.edu/lecture/github-issues/#tips) for all the tips.
