### ISSUE TITLE
What is the deal with the >> ?

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/RubberDuck#279]
It does not seem to do anything....

![image](https://user-images.githubusercontent.com/228704/230668713-03660774-6294-47dd-9af6-bb062d78eab9.png)

**Comment by OTBond** [comment]
That is the speed buff, it works if you collide with it. Slightly increases player speed, but if you look closely it definitely does something! There is a slight chance (10%) for it to slow you down slightly instead (fake powerup).
