### ISSUE TITLE
Walls spawn in a way which makes it impossible for player to pass

### ISSUE THREAD

**Issue by ekbritt99** [SCCapstone/RubberDuck#282]
I was able to encounter this bug many times whether it was at very quickly after starting the level (~10 seconds) or much later. As you can see in the screenshot, it's impossible for the player to pass as there is not enough space in between the walls for the player.
![image](https://user-images.githubusercontent.com/70303464/231332597-870af3a7-afb1-416e-ada6-aadc334f029c.png)

**Comment by OTBond** [comment]
This one was resolution specific - I don't have a monitor small enough to test but changed the way blocks spawn to be limited based on half the screen height / (2 * Block height) -1 so there should always be a gap at least 2 blocks tall in the center.
