### ISSUE TITLE
Walls continue to spawn even when game is paused

### ISSUE THREAD

**Issue by ekbritt99** [SCCapstone/RubberDuck#283]
Left the game paused for a couple minutes. When I came back the screen was filled with walls even though the game was still paused. I was able to recreate this bug multiple times by pausing the game, waiting ~2 minutes and then the walls would begin spawning again without ever stopping.
![image](https://user-images.githubusercontent.com/70303464/231333344-21666dc4-e4c1-4d74-9d70-d4f57ab710fb.png)

https://user-images.githubusercontent.com/70303464/231335336-aaf1c81f-79a9-4a85-ac91-c811f0e65cae.mp4

**Comment by j-bis** [comment]
Leaving the game paused also leaves enemies spawning. This is after leaving the game for ~3 minutes and unpausing, they will roll onto the screen but do not move. This also lags the game a lot.
![vlcsnap-2023-04-16-18h33m52s687](https://user-images.githubusercontent.com/29241004/232346436-d90afc10-5320-47a4-ac4a-9d6362e1cee7.png)

https://user-images.githubusercontent.com/29241004/232346638-e81f510b-4587-4a56-9d72-5a709ca56c5b.mp4
