### ISSUE TITLE
Player hats do not stay saved as purchased when player base skin is swapped and are no longer displayed.

### ISSUE THREAD

**Issue by ekbritt99** [SCCapstone/RubberDuck#284]
Got enough coins to get the blue base skin. It displays correctly while playing in level. When I went to the customize menu, the base skin did not reflect that I had the blue base skin equipped and still showed the default one. I bought the gold chain "hat" and equipped it. Then I equipped the blue base skin again just to make sure that my player would stay blue. I went to play another level (you can also see how the bug for walls spawning in a way that the player cannot pass occurs almost right away), and my player was blue but without the chain. I went back to the customize menu and the chain was no longer equipped and I had to buy it again if I wanted to equip it (my coins that were used to purchase it were still gone as well).

https://user-images.githubusercontent.com/70303464/231342332-3569ee2b-f22c-4dc6-8078-bfde4547117a.mp4

**Comment by cSwiggitySwooty** [comment]
The hats are skin-specific. For example, purchasing the blue duck with the gold chain does not unlock the yellow duck with the gold chain. I have slightly changed the UI to make this a little more clear and show which skins are equipped and which are not.
