### ISSUE TITLE
Not all collisions with enemies cause damage to the player

### ISSUE THREAD

**Issue by ekbritt99** [SCCapstone/RubberDuck#285]
Was able to recreate this bug many times. When the player collides with several enemies in rapid succession, only the first collision causes damage to the player even though all the enemies disappear. In the video, you can see I had 2 hearts when I collided with 3 enemies. My player only took 1 heart of damage even though I collided with 3 enemies.

https://user-images.githubusercontent.com/70303464/231343192-e2f36456-58ad-4c6a-be7f-5035b4b6a1df.mp4

**Comment by OTBond** [comment]
Intended - you can see that the player flashes a bit after being hit to signal a small grace period.  This prevents the player from being one-shot by a pile of enemies.
