### ISSUE TITLE
Player Name is off center and hard to interact with

### ISSUE THREAD

**Issue by cdrez** [SCCapstone/RubberDuck#290]
This might be because I am using an ultrawide monitor. It is off center and also hard to click and type in a new name. Sometimes it lets me delete characters and sometimes it wont and I have to spam click and keep trying.

![image](https://user-images.githubusercontent.com/55902670/232245937-6ab0d4da-e741-482f-8379-51a13066e834.png)

**Comment by bgrose** [comment]
Pygame set up to mix with ultrawide in all aspects would be out of scope of project, some improvements like text will be made
