### ISSUE TITLE
No support for multiple resolutions

### ISSUE THREAD

**Issue by ChristianRios1** [SCCapstone/RubberDuck#291]
There is no support for resolutions other than fullscreen, which causes some graphical issues for the player.
![Screenshot (53)](https://user-images.githubusercontent.com/77369228/232334383-c08ad520-b8c3-4127-80ad-88fdb50a9115.png)

With an ultrawide monitor, the different buttons (and their hitboxes for clicking on them) change, so hovering over a button may not be clickable unless it is in a specific spot.

![Screenshot (55)](https://user-images.githubusercontent.com/77369228/232334679-e11a3000-32f6-4450-b3ce-527f034a025c.png)

There is a slight graphical issue with the spacing between the number and the player's name, which I am assuming is a result of the unexpected resolution.

However, the game runs nicely and is only a quality of life improvement for users with a non-standard monitor, so it's just a suggestion to enhance the user experience and not a huge problem.

**Comment by bgrose** [comment]
Windowed game and ultrawide support is out of scope of this project at this moment due to no ultra wide testing available and time to implement
