### ISSUE TITLE
Coins disappear on pausing and walls reducing

### ISSUE THREAD

**Issue by j-bis** [SCCapstone/RubberDuck#293]
Having the game paused for a short period of time (roughly 10 seconds) will remove coins from the screen. Sometimes a wall will also become shorter.
https://user-images.githubusercontent.com/29241004/232346116-c349c39d-d539-4e0f-9ae4-d63e7e8c7e82.mp4

**Comment by OTBond** [comment]
Can't recreate - likely a product of memory issues brought on by the infinite level generation bug when paused. Closing for now
